[PackageBundlerExampleRegistry]
git-tree-sha1 = "36962bd1405e0d3ddcad5ffb7be414410d4ec1aa"

    [[PackageBundlerExampleRegistry.download]]
    sha256 = "83d3edd2342cb33512f167add4594aa1b8cfc57ef31a175d06348e504c9c0710"
    url = "https://github.com/MichaelHatherly/package-bundler-builder-example/releases/download/1.0.0/PackageBundlerExampleRegistry.tar.gz"
