name = "PackageBundlerProviderExample"
uuid = "399f630a-f3ad-4bd8-85c1-3531b936279c"
authors = ["MichaelHatherly <michaelhatherly@gmail.com>"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
