name: CI
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read

jobs:
  finalize:
    timeout-minutes: 10
    needs: [test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo test: ${{ needs.test.result }}
      - run: exit 1
        if: |
          (needs.test.result != 'success')

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      JULIA_PKG_SERVER: "pkg.julialang.org"
      JULIA_DEPOT_PATH: ${{ github.workspace }}/CustomJuliaDepot
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          persist-credentials: false

      - uses: julia-actions/install-juliaup@5e96cfab3bb0500aa42f2843f46c24b91cfcc3cd
        with:
          julia-version: "1"

      # Ensure that the General registry is added, since this is a non-standard depot.
      - run: julia -e 'import Pkg; Pkg.Registry.add(Pkg.Registry.DEFAULT_REGISTRIES)'
 
      - run: julia --project=. -e 'import Pkg; Pkg.instantiate()'

      - run: julia --project=. -e 'import PackageBundlerProviderExample; PackageBundlerProviderExample.install()'
        env:
          JULIA_NUM_PRECOMPILE_TASKS: 1

      - run: julia +1.10.1 --project=@bundled@v1.0.0 -e 'using CairoMakie; scatter(1:3, 1:3)'
      - run: julia +1.10.2 --project=@bundled@v1.1.0 -e 'using CairoMakie; scatter(1:3, 1:3)'
      - run: julia +1.9.4  --project=@bundled@v1.2.0 -e 'using CairoMakie; scatter(1:3, 1:3)'

      - run: julia --project=. -e 'import PackageBundlerProviderExample; PackageBundlerProviderExample.remove()'
